//
//  Gobelieve.h
//  Gobelieve
//
//  Created by ch999 on 2021/4/16.
//

#import <Foundation/Foundation.h>

//! Project version number for Gobelieve.
FOUNDATION_EXPORT double gobelieveSDKVersionNumber;

//! Project version string for Gobelieve.
FOUNDATION_EXPORT const unsigned char gobelieveSDKVersionString[];

// Generated by:
// find Sources -name "*.h" | sort -f | xargs basename | xargs printf "#import <Gobelieve/%s>\n"

//#import <Gobelieve/interf_dec.h>
//#import <Gobelieve/interf_enc.h>
//#import <Gobelieve/wavreader.h>
//#import <Gobelieve/wavwriter.h>
//#import <Gobelieve/wav_amr.h>
#import <Gobelieve/NSDate+Format.h>
//#import <Gobelieve/NSString+JSMessagesView.h>
#import <Gobelieve/CustomerMessageDB.h>
#import <Gobelieve/EPeerMessageDB.h>
#import <Gobelieve/GBConversationIterator.h>
#import <Gobelieve/GroupMessageDB.h>
#import <Gobelieve/IMessageDB.h>
#import <Gobelieve/IMessageIterator.h>
#import <Gobelieve/PeerMessageDB.h>
#import <Gobelieve/SQLConversationDB.h>
#import <Gobelieve/SQLCustomerMessageDB.h>
#import <Gobelieve/SQLGroupMessageDB.h>
#import <Gobelieve/SQLPeerMessageDB.h>
//#import <Gobelieve/Gobelieve.h>
#import <Gobelieve/CustomerMessageHandler.h>
#import <Gobelieve/GroupMessageHandler.h>
#import <Gobelieve/PeerMessageHandler.h>
#import <Gobelieve/SyncKeyHandler.h>
#import <Gobelieve/IMHttpAPI.h>
#import <Gobelieve/IMService.h>
#import <Gobelieve/Message.h>
#import <Gobelieve/Conversation.h>
#import <Gobelieve/ICustomerMessage.h>
#import <Gobelieve/IMessage.h>
#import <Gobelieve/IUser.h>
#import <Gobelieve/MessageACK.h>
#import <Gobelieve/MessageAttachment.h>
#import <Gobelieve/MessageAudio.h>
#import <Gobelieve/MessageContent.h>
#import <Gobelieve/MessageFile.h>
#import <Gobelieve/MessageGroupNotification.h>
#import <Gobelieve/MessageGroupVOIP.h>
#import <Gobelieve/MessageHeadline.h>
#import <Gobelieve/MessageImage.h>
#import <Gobelieve/MessageLink.h>
#import <Gobelieve/MessageLocation.h>
#import <Gobelieve/MessageNotification.h>
#import <Gobelieve/MessageP2PSession.h>
#import <Gobelieve/MessageRevoke.h>
#import <Gobelieve/MessageSecret.h>
#import <Gobelieve/MessageText.h>
#import <Gobelieve/MessageTimeBase.h>
#import <Gobelieve/MessageVideo.h>
#import <Gobelieve/MessageVOIP.h>
#import <Gobelieve/TAHttpOperation.h>
#import <Gobelieve/AsyncRawTCP.h>
#import <Gobelieve/AsyncSSLTCP.h>
#import <Gobelieve/AsyncTCP.h>
#import <Gobelieve/TCPConnection.h>
#import <Gobelieve/FileCache.h>
#import <Gobelieve/GOReachability.h>
#import <Gobelieve/MessageCoordinator.h>
//#import <Gobelieve/util.h>
